# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bbsystem.User'),
            preserve_default=False,
        ),
    ]
